apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:
      containers:
      - name: ml-pipeline
        image: ml-pipeline:latest
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
spec:
  selector:
    app: ml-pipeline
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 