apiVersion: apps/v1
kind: Deployment
metadata:
  name: raft-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raft-simulator
  template:
    metadata:
      labels:
        app: raft-simulator
    spec:
      containers:
      - name: raft-simulator
        image: raft-simulator:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: raft-simulator
spec:
  selector:
    app: raft-simulator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 