apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: agentml
  name: agentml-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agentml-app-rolebinding
  namespace: agentml
subjects:
- kind: ServiceAccount
  name: default
  namespace: agentml
roleRef:
  kind: Role
  name: agentml-app-role
  apiGroup: rbac.authorization.k8s.io
